---
repo-name: peripherals-kinetic-brigdehub
categories:
- Integration
- Automation
display-name: Kinetic Bridgehub
manufacture: Kinetic Data
product: Bridgehub
description: The real-time integration component of the Kinetic Platform.
